### ISSUE TITLE
Add support for renaming files & their links

### ISSUE THREAD

**Issue by Craftidore** [Yakitrak/obsidian-cli#1]
While I realize this couldn't be done by utilizing the Obsidian URI, but one of the biggest problems I've had while working with my Obsidian vault from the command line is that when renaming files, links aren't updated as well. 

This greatly reduces my ability to bulk-rename files (like when I was going through my vault and replacing all spaces in filenames with `-`). 

## Feature Request: A command to rename a file and also change all linked mentions to the new name

**Feature Request**: A straightforward way to rename a file in a vault and have the links to that file in in all other `.md` files in the vault to the new name.

**Comment by Yakitrak** [comment]
Hi @Craftidore, I have just released a new version which has a move/rename command doing what you wanted. It is new and experimental right now so any feedback would be appreciated!
