### ISSUE TITLE
`obs move` tries to change files inside of `.` folders

### ISSUE THREAD

**Issue by Craftidore** [Yakitrak/obsidian-cli#10]
## Expected Behavior

`obs move` will not change files that Obsidian doesn't recognize (namely folders and files that start with `.`). 

## Current Behavior

`obs move` tries to change the files inside of folders and files starting with `.`, which are files and folders which Obsidian ignores.

## Context

This is specifically a problem since I use git to track changes, so `obs move` attempts to change a blob which is read-only, crashes, and doesn't actually update the other files. 
I wouldn't be surprised if this also attempts to change values in `.obsidian/`, which could mess with plugin data if they're storing text that has that link in it.

## System Info

- OS: EndeavourOS Linux x86_64
- Kernel: 6.2.2-arch2-1
- Shell: bash 5.1.16
- CPU: Intel iy-10700 (16) @ 4.800GHz
- GPU: NVIDIA GeForce RTX 2060 Rev. A
- Memory: 32 GB
- Terminal: alacritty
- obsidian-cli version: v0.1.1 (from `obsidian-cli_0.1.1_linux_amd64.tar.gz`, verified with sha256sum according to checksums.txt)

**Comment by Yakitrak** [comment]
Thank you for the feedback! Could you give me an example of what happens as I didn't quite understand, or how I could reproduce this? I also use `git` to track my vault too.

**Comment by Craftidore** [comment]
`TestingNote.md`
```markdown
## Using `___`

So iCloud sync is too slow...
___

So here's onedrive

## Using `***`

So iCloud sync is too slow...
***
So here's onedrive

[[test-of-move]]

```
`test-of-move.md`
```
<empty>
```
Command:
```bash
obs move test-of-move test-of-move2
```

```
Moved note
		from /home/craftidore/Main-Obsidian-Vault/test-of-move.md
		to /home/craftidore/Main-Obsidian-Vault/test-of-move2.md
2023/03/17 12:20:25 open /home/craftidore/Main-Obsidian-Vault/.git/objects/00/3100b9155bf0f45236143c53a9af6af6b60ea4: permission denied
```

I'm a bit busy right now, but later today I'll make a test vault backed up with git where it's reproduced so I don't have to share my entire vault.

**Comment by Yakitrak** [comment]
I think I see the issue, and I will take a look when I am free but do let me know if you setup a test vault as would be a good way to confirm the fix. I will (and should have originally) ignored the any directories starting with `.` when updating links. 
I didn't think it would be an issue as `.git` or `.obsidian` store files in JSON format and wouldn't have a link in the format of `[[NoteName]]`.

**Comment by Yakitrak** [comment]
https://github.com/Yakitrak/obsidian-cli/pull/11 is merged in and new release is ready on homebrew and Github. Please let me know if it works for you and I'll wait for your confirmation before closing issue. Thank you again for the feedback!

**Comment by Craftidore** [comment]
I can confirm this works as intended now!
