### ISSUE TITLE
Easy Installation for Windows

### ISSUE THREAD

**Issue by Yakitrak** [Yakitrak/obsidian-cli#15]
## Description

Currently the installation process for Mac and Linux is running 2 commands and its setup. However for Windows, the process is manual, having to download the latest zip, unzip it and set it to path. Unfortunately I don't own a Windows desktop so this is hard for me to do (and test) but the task is if anyone is up for it to contribute by setting up easy installation for Windows devices. This will likely be using one of the package managers (Chocolaty, Scoop, Winget).

**Comment by Yakitrak** [comment]
Added https://github.com/Yakitrak/obsidian-cli/commit/4439683c8405fde343ff1cf25268a28d8a4fc6e3

**Comment by sergeevabc** [comment]
I built obsidian-cli.exe from source, but cannot make it work with Obsidian portable (not in Program files or User's profile, but on USB stick).

``` console
$ obsidian-cli set-default "Obsidian"
Failed to read Obsidian config file. Please ensure vault has been set up in Obsidian.

$ obsidian-cli set-default D;\Obsidian
Failed to read Obsidian config file. Please ensure vault has been set up in Obsidian.
```

**Comment by sergeevabc** [comment]
I launched Obsidian app, the only vault I have is opened, its name is, well, Obsidian. Then I switch back to command line shell and launch ` $ obsidian-cli set-default Obsidian`. And the same error is displayed: `Failed to read Obsidian config file. Please ensure vault has been set up in Obsidian.`

**Comment by Yakitrak** [comment]
Can you please try to open another folder in Obsidian and try to set that as default - does that work? It looks like its not setup correctly in Obsidian for you to see that error.

**Comment by sergeevabc** [comment]
![](https://github.com/user-attachments/assets/755b091c-bc00-4df9-b5c5-f79d1b5fb0d1)

``` console
obsidian-cli.exe set-default Vault
Failed to read Obsidian config file. Please ensure vault has been set up in Obsidian.
```

It would be better to be able to specify the path to the configuration file, rather than expecting the program to find it by itself successfully every time.
