### ISSUE TITLE
Support for generating day notes (Obsidian Calendar, and Template / Templater plugins)

### ISSUE THREAD

**Issue by tedmiston** [Yakitrak/obsidian-cli#19]
**Is your feature request related to a problem? Please describe.**

I was very excited to find this CLI as I have been looking for something like this for a while. 
 My desired use case is to use the CLI to create / open day notes, e.g., `<vault root>/days/2023-06-21.md`.  Day notes are rendered from a day template for each calendar day, e.g., `/templates/day.md`.

**Expected**: I was hoping when I asked the CLI to create a note for `YYYY-MM-DD` that it would automatically pick up on the day note naming format and know that it should create a day note from the template and in the configure day notes folder.

**Actual**: What the CLI does today, instead, when running `obs create 2023-06-21` is: create an empty note at the root named e.g., `2023-06-21.md`.

**Describe the solution you'd like**

I would like `obs` to automatically generate the daily note file when passed the appropriate args.  Maybe that is: `obs create 2023-06-21` or `obs create --day 2023-06-21` etc.

The [Obsidian Calendar plugin](https://github.com/liamcain/obsidian-calendar-plugin) provides a convenient way to generate and navigate daily notes.  It is one of the [most popular](https://github.com/topics/obsidian-plugin) community plugins, and many Obsidian users use this every day.

The Calendar plugin can be used with either the built-in Templates core plugin or a more advanced external one such as [Templater](https://github.com/SilentVoid13/Templater) (another of the most popular plugins).  [The Templater plugin is configured to trigger on new file creation, so there should not need to be anything specific done for that vs the default Templates plugin... it should "just work".]

**Describe alternatives you've considered**

Open Obsidian and create the new day note in the GUI.

**Additional context**

**Comment by Yakitrak** [comment]
Thank you for the feedback! I personally don't make use of the calendar plugin or daily notes in a traditional way but this seems like a great idea. I will add this as a feature request but unfortunately I won't be able to start on this in the foreseeable future. If you (or anyone else) know Go, please feel free to contribute.

**Comment by Yakitrak** [comment]
As Obsidian URI now provide support for daily notes (with templates), the latest release now has added this as a new command: https://github.com/Yakitrak/obsidian-cli/releases/tag/v0.1.8
