### ISSUE TITLE
Setting default vault for Obsidian flatpak installation

### ISSUE THREAD

**Issue by d9k** [Yakitrak/obsidian-cli#20]
```
> obs set-default /home/d9k/tx
2023/06/26 11:35:54 Failed to read Obsidian config file. Please ensure vault has been set up in Obsidian

> flatpak list
Obsidian           md.obsidian.Obsidian             1.3.5      stable      system
```

`Ubuntu 22.04`

**Comment by Yakitrak** [comment]
When setting the vault, you need to pass the name of the vault (which would be directory), not the path. For example in your case, it will be `obs set-default tx`. As long as you've opened this vault in the Obsidian application previously, `obs` will be able to find the path automatically. Please let me know if this works or if you have any other issues.

This is explained more here: https://yakitrak.github.io/obs/docs/commands/set-default-vault

**Comment by d9k** [comment]
@Yakitrak , not working

```
> obs set-default tx
2023/07/01 17:02:00 Failed to read Obsidian config file. Please ensure vault has been set up in Obsidian
```

Please explain how to use `obs` with Obsidian flatpak installation.

The command to run obsidian is:

```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=obsidian.sh --file-forwarding md.obsidian.Obsidian
```

**Comment by Yakitrak** [comment]
@d9k I am not familiar with flatpak installation but assuming you have definitely opened up the `tx` vault with Obsidian beforehand and are still getting this error, I would assume that the config file create by Obsidian is not in standard configuration directory so `obs` is struggling to find it. Would it be possible to install Obsidian in an alternative method (such as Deb file) and see if the issue persists). 

Looking at the [Obsidian Linux download page](https://obsidian.md/download) it seems flatpak installation is community maintained so definitely worth trying another installation if possible?

**Comment by d9k** [comment]
ok, it works with deb-installation, thx.

But issue "Setting default vault for Obsidian flatpak installation" is not solved.

Feel free to close an issue if you don't plan to fix it anytime soon.
