### ISSUE TITLE
It opens Obsidian on `--append` even without `--open` flag.

### ISSUE THREAD

**Issue by Kalabasa** [Yakitrak/obsidian-cli#21]
**Describe the bug**
Running `obs create "test" --append --content test` opens the Obsidian app without the `--open` flag set.

**To Reproduce**
Steps to reproduce the behaviour:
1. `obs create "test" --append --content test`
3. `obs version v0.1.5`
5. Have an existing note named "test"

**Expected behaviour**
It should append to the note but not open it.

**Additional context**
I'm trying to use the CLI as a very quick set-and-forget note taking. I already have a terminal hotkey and have aliased the command so it would be very quick, but opening the Obsidian GUI breaks that flow.

**Comment by Kalabasa** [comment]
Just skimmed through the code. Looks like this is an issue with the underlying Obsidian URI ignoring the `silent` flag? Is this confirmed? If so I'll move this issue to Obsidian project itself.

**Comment by Kalabasa** [comment]
Oh, @yakitrak actually reported it! Closing this one then. 😅 
https://forum.obsidian.md/t/obsidian-uri-new-action-silent-flag-not-working-correctly/59690

**Comment by Yakitrak** [comment]
@Kalabasa, yes I discovered the same issue and posted on the forum. Its not clear from the official docs but the `open` parameter is for the note itself, not the Obsidian application. Basically, it will always open the Obsidian vault when you create a note with the `create`, but if you use `open` parameter, it would open the created note.
