### ISSUE TITLE
"obs ." to open the current directory

### ISSUE THREAD

**Issue by classicrob** [Yakitrak/obsidian-cli#23]
**Is your feature request related to a problem? Please describe.**
I'm frustrated by how slow and inconvenient it is to open vaults through the GUI

**Describe the solution you'd like**
"obs ." to open the current directory as a vault

**Comment by Yakitrak** [comment]
Thank you for the feedback! This is not currently in scope of the tool as its purpose is to open vaults which are already recognise by Obsidian (the tool reads from the Obsidian config itself which stores vault path). I also taking a break from adding features to this tool (I am happy to do bug fixes if raised) so I will tag this as a feature request for the future.

**Comment by classicrob** [comment]
Can you point me maybe to where I would need to edit code to do it myself?

**Comment by jimbrig** [comment]
@classicrob are you on Windows? If so see my Post in the Obsidian Forum [Created a Custom Obsidian Vault Launcher for a Registered `.vault` Extension (Windows)](https://forum.obsidian.md/t/created-a-custom-obsidian-vault-launcher-for-a-registered-vault-extension-windows/52344?u=jimbrig2011) or on [Reddit](https://www.reddit.com/r/ObsidianMD/comments/10c61ml/created_a_custom_obsidian_vault_launcher_for_a/).

Works great for me

**Comment by Yakitrak** [comment]
Closing issue - as mentioned this tool is intended to be used with existing vaults and there are work arounds shared above.
