### ISSUE TITLE
Add shortcut strings to usage.png

### ISSUE THREAD

**Issue by RichardLitt** [Yakitrak/obsidian-cli#24]
**Is your feature request related to a problem? Please describe.**

Right now, I want to use the shortcuts, but it wasn't clear to me without checking the source code that, for instance, `obs o example.md` would work. I had tried `-o` and received no helpful note that it should just be `o`. 

**Describe the solution you'd like**

Add the aliases the to `usage.png` which is the help doc. 

**Describe alternatives you've considered**

Manually adding strings that print when each command is called. Seems less efficient. Happy to make a PR for that, though.

**Comment by Yakitrak** [comment]
Thank you for the feedback! In case you didn't know, you can check aliases by typing the command you want to alias following by `--help`. For example "obs open --help" will show you the alias for the command and all the flags: 
![image](https://github.com/Yakitrak/obsidian-cli/assets/15147598/8aac3636-493a-4e6e-810f-7574279cec41)

I am not 100% sure if there is a way to show the flags from the main help menu, but if you want to make a PR for it, please go ahead!

**Comment by RichardLitt** [comment]
I think I just misunderstood that the alias does not mean a flag. Thinking about it further, this one is on me. The software is fine as it is. :) Thank you for your response!
