### ISSUE TITLE
Open in Read Mode

### ISSUE THREAD

**Issue by SuperMB** [Yakitrak/obsidian-cli#25]
**Is your feature request related to a problem? Please describe.**
When opening a file from CLI, obsidian seems to open the note in either editor or reader, whichever was opened last. However, we need to open our notes in reader.

**Describe the solution you'd like**
An additional flag for the open command that would specify to force the reader, or editor, view.

**Comment by Yakitrak** [comment]
This is a great suggestion @SuperMB and one I'd also find useful but currently [Obsidian URIs](https://help.obsidian.md/Concepts/Obsidian+URI) which is what this tool uses to open Obsidian, does not provide a way to do this.

**Comment by SuperMB** [comment]
@Yakitrak thanks for letting me know. Does obsidian provide a way to open the app and select the editing or reading mode? If so, this would enable us to use as desired. One could open the app, select the desired mode, and then open the desired file.

**Comment by Yakitrak** [comment]
I am not actively using Obsidian anymore so I am not 100% sure but I believe there is an option to select default view mode on the settings. Once set it should open files in that mode. Maybe that could work for you?
