### ISSUE TITLE
every command opens the note in Obsidian

### ISSUE THREAD

**Issue by marwal-88** [Yakitrak/obsidian-cli#27]
**every command fetches Obsidian to current workspace and gives it focus**

**To Reproduce**
1. Place Obsidian on workspace 3
2. Go to workspace 1 and open a term
3. type 'obs create test_note' 

**Expected behavior**
The Obsidian app should remain in the state it is unless you use '--open'

**Screenshots**

**Additional context**
I use Linux, Manjaro; Obsidian 1.5.8-2; obs v0.1.6; Window Manager xfce-4

**Comment by Yakitrak** [comment]
This is the default behaviour of the [Obsidian URI](https://help.obsidian.md/Concepts/Obsidian+URI) as it opens the app to perform the action. The `--open` flag only affects if it opens the specific note or not.
