### ISSUE TITLE
The name of the command, obs, clashes with that for OBS Studio

### ISSUE THREAD

**Issue by ghost** [Yakitrak/obsidian-cli#28]
**Is your feature request related to a problem? Please describe.**
I have OBS Studio installed on my Linux desktop, and the cli command for that is `obs`. This clashes with command for Obsidian CLI

**Describe the solution you'd like**
Rename the binary to `obsidian-cli` (or something similar).

**Describe alternatives you've considered**
`sudo mv /usr/bin/obs /usr/bin/obsidian-cli` and `sudo mv /usr/bin/obs /usr/bin/obs-studio` Both work, but is a kludge at best.

**Additional context**

**Comment by Yakitrak** [comment]
Hi, thanks for the feedback, I didn't realise when I made this but I have been meaning to do this. I am not actively developing this tool at the moment - if you're able to make a PR I'd be happy to approve.

**Comment by aspauldingcode** [comment]
came here to say this too

**Comment by Yakitrak** [comment]
This PR is being worked on: https://github.com/Yakitrak/obsidian-cli/pull/31

**Comment by Yakitrak** [comment]
PR merged, will do a release shortly, thanks!
