### ISSUE TITLE
"$obs create test" Opens a "Vault not found window" After setting the default vault

### ISSUE THREAD

**Issue by mssevov18** [Yakitrak/obsidian-cli#29]
**To Reproduce**
Steps to reproduce the behaviour:
1. obs create test
2. No flags used
3. Version 0.1.6 installed from AUR
4. Brand new vault

I expected a new file called "test" to appear in the vault.

![image](https://github.com/Yakitrak/obsidian-cli/assets/49585945/49e10383-d725-48d7-8bca-df7c604db1bb)

**Comment by Yakitrak** [comment]
Hi, thanks for the feedback. Have you opened the vault in Obsidian before you using the CLI as thats a requirement? Or has the path of the vault changed that was your default vault? Try this: https://github.com/Yakitrak/obsidian-cli?tab=readme-ov-file#set-default-vault

**Comment by mssevov18** [comment]
The default path is correct. I tried to do `$obs create test` and I get the same error again. I don't know what the issue might be.

**Comment by Yakitrak** [comment]
Does it work when you pass a vault with `--vault`? Did it work previously and it has stopped working? Any information would help debug this.
