### ISSUE TITLE
Create pre configure Vault with CLI

### ISSUE THREAD

**Issue by darkr4y** [Yakitrak/obsidian-cli#33]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Vaults can be created and, like vscode, a customized list of plugins can be installed, as well as the default configuration can be modified
Or execute some additional shell commands to complete the auxiliary
This can all be done via configuration files。

**Comment by Yakitrak** [comment]
Thanks for the feedback but I an not sure I understand it. This sounds like a feature request to add a command to create a vault, install plugins etc. But unfortunately that is not possible with this CLI as its built on top of [Obsidian URIs](https://help.obsidian.md/Extending+Obsidian/Obsidian+URI) that only have actions for interacting with notes
