### ISSUE TITLE
New line doesn't get interpreted inside `--content`

### ISSUE THREAD

**Issue by danielwerg** [Yakitrak/obsidian-cli#34]
obsidian-cli version v0.1.7

Maybe flag count be added to interpret?

**To Reproduce**

1. `obsidian-cli create "{NOTE}" --append --content "\nprint this in new line"`
2. See below

Before:
```
Blah blah blah
```

After:
```
Blah blah blah\nprint this in new line
```

**Expected behaviour**

```
Blah blah blah
print this in new line
```

**Additional context**

I have tried `obsidian-cli create "{NOTE}" --append --content "\\nprint this in new line"` with no luck

**Workarounds**

```sh
obsidian-cli create "{NOTE}" --append --content "$(echo -e "\nprint this in new line")"
```

```sh
obsidian-cli create "{NOTE}" --append --content "
print this in new line"
```

**Comment by Yakitrak** [comment]
Thanks for the feedback, this is a good idea and should definitely be added. It shouldn't take long, but I am not actively working on this project right now but if you're able to make a PR, that would be amazing.

**Comment by Yakitrak** [comment]
Latest release handles this among other characters: https://github.com/Yakitrak/obsidian-cli/releases/tag/v0.1.8

Thanks for raising this!
