### ISSUE TITLE
How to open a vault without specifying a file?

### ISSUE THREAD

**Issue by Sleepful** [Yakitrak/obsidian-cli#37]
just want to open a given vault, sometimes I don't know the files inside it :)

**Comment by Yakitrak** [comment]
Unfortunately there isn't a specific command for this but you could try to just do the `open` command with what you think the note might be or any random work like this `obsidian-cli open anything`. This will open the obsidian vault (as long as its setup), and just display a message saying note could not be found but you'll still be in the vault.

**Comment by Sleepful** [comment]
thanks! I think using the dot `.` as the file name is working fine. 

I was running the command from the terminal and something else I noticed is that the Obsidian window is not focused after opening a file. Are you aware of some way to focus it after opening? thanks

**Comment by Yakitrak** [comment]
No problem! I just tried again to confirm and it does auto focus the window after running the open command. I am on Mac so might be different on different OS.
