### ISSUE TITLE
Is this project installable on a Termux GNU/Linux host and/or Termux GNU/Linux  proot chroot environment?

### ISSUE THREAD

**Issue by b9Joker108** [Yakitrak/obsidian-cli#38]
**Is this project installable on a Termux GNU/Linux host and/or Termux GNU/Linux  proot chroot environment?**

I wish to interact with Obsidian via the Termux CLI and I am wondering if your project is workable in order to realise this. It would make scripting prototype Obsidian plugins easy to realise.

**Describe the solution you'd like**
I would really like this project to be installable on Termux, would anything in your knowledge preclude it from being done on an unrooted device?

**Additional context**
I am not currently adept at Go, but it is on my TODO list.

**Comment by b9Joker108** [comment]
I went along and installed it in a Termux host and it was staightforward:

```shell
pkg up
pkg i git golang
```
Then, initialize Go by exporting the following environment variables in your shell configuration files, for example:  ~/.profile, ~/.bashrc, or ~/.zshrc by adapting the filepath referenced according to where you want `go` projects to be housed on your system:

```shell
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
```

Then source shell configuration, for example:

```shell
source ~/.profile
```

```shell
git clone https://github.com/Yakitrak/obsidian-cli.git
cd obsidian-cli
go build
```

Add the locally git cloned project to your shell PATH environment variable and source.

Check install:

```shell
obsidian-cli --help
```

**Comment by b9Joker108** [comment]
I haven't yet really used `obsidian-cli` since I installed it, but I just found out about the auto-generated shell command completions script. Zsh is my daily driver in my Termux host, so I have made it a Zsh module to my .zshrc. I musy say, I didn't know generating a project completions script to integrate with shell auto-completions was even possible and you have realised it for a few shells. That is a real finesse that I appreciate.

**Comment by Yakitrak** [comment]
Hey thanks for the feedback. And yes `cobra` really made things easy to make a CLI. This is my first Golang project that I mostly did to learn and to make an Obsidian tool for myself so quite happy to see how useful its become over time. Good note on the completion script, I'll add it to the instructions soon.

Also its good to see you managed to install this for Termux from source but just so you know if you wanted an easier method, I believe you could have just downloaded and set this on your path from here `https://github.com/Yakitrak/obsidian-cli/releases/latest`. Doing it from source like you did is great but unless you're using Go, its adding dependancies you didn't need.
