### ISSUE TITLE
Example of set-default

### ISSUE THREAD

**Issue by RichardLitt** [Yakitrak/obsidian-cli#4]
I'm having issues with the `set-default` command. I am on OSX. 

```
➜  docs git:(master) ✗ obs set-default "/Users/richard/docs/.obsidian"
Setting vault location as default:  /Users/richard/docs/.obsidian
# Doesn't work
➜  docs git:(master) ✗ obs set-default "\/Users\/richard\/docs\/.obsidian"
Setting vault location as default:  \/Users\/richard\/docs\/.obsidian
```

This won't work adequately. I must be missing something. Any ideas? 

Seems to be an escaping issue. Attaching screenshot.

<img width="361" alt="Screenshot 2023-03-13 at 03 03 13" src="https://user-images.githubusercontent.com/910753/224591621-59c2bab4-3008-4fc3-bd0b-bbc646e25f00.png">

**Comment by Yakitrak** [comment]
Hi, apologies for the late reply. What is the name of your actual vault? For example if your vault is called "test-vault", it doesn't matter what the path of the vault is, it will automatically work it if you do `obs set-default "test-vault". The only prerequisite is that you have opened that vault in obsidian first (you only need to do this step once) prior to using this command. 

Let me know if that works or if you have any other issues.

**Comment by RichardLitt** [comment]
Ahhh. Right, got it. Set it to `obs set-default docs` and it works fine now.

The only issue is that `obs open file.md` will not work on any documents not in that vault, even if I am in the correct folder for `file.md`. Is that expected?

**Comment by Yakitrak** [comment]
Glad its working! Yes thats correct, the cli is is only intended to interact with Obsidian vaults, the directory you are currently in with your terminal is not used in anyway.

**Comment by Yakitrak** [comment]
Documentation updated: https://github.com/Yakitrak/obsidian-cli/pull/9
